on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - main
name: ci
jobs:
  check-clippy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  check-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt

  build-and-publish:
    runs-on: ubuntu-20.04
    needs:
      - check-clippy
      - check-format
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cargo publish --dry-run
      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
        if: github.ref == 'refs/heads/main'
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
